services:
  minio:
    image: 'minio/minio'
    restart: on-failure
    command: server /data --console-address ":9001" --address ":80"
    ports:
      - '8081:80'
      - '9001:9001'
    volumes:
      - ./testroot-s3:/data
  mysql:
    image: 'mysql'
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: nepheleroot
      MYSQL_DATABASE: nephele
      MYSQL_USER: nephele
      MYSQL_PASSWORD: nephele
    volumes:
      - ./testroot-mysql:/var/lib/mysql
